[project]
name = "can-bus-web-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cantools>=40.2.3",
    "python-can>=4.5.0",
    "streamlit>=1.46.1",
]
